Repository triton-inference-server/server, pull requests merged in 2024-12, with the labels that each got.

#7840 fix: gRPC segfault due to Low Request Cancellation Timeout
  qa/L0_grpc_state_cleanup/test.sh
  qa/L0_request_cancellation/grpc_cancellation_test.py
  qa/L0_request_cancellation/test.sh
  src/grpc/infer_handler.cc
  src/grpc/infer_handler.h
  src/grpc/stream_infer_handler.cc
  src/grpc/stream_infer_handler.h
Labels: PR: fix

#7859 ci: RHEL8 L0_backend_python Support
  build.py
  qa/L0_backend_python/common.sh
  qa/L0_backend_python/env/test.sh
  qa/L0_trt_compat/test.sh
Labels: PR: ci

#7866 test: Fix requested output deleting extra outputs
  qa/L0_backend_python/io/io_test.py
  qa/L0_backend_python/io/requested_output_model/config.pbtxt
  qa/L0_backend_python/io/requested_output_model/model.py
  qa/L0_backend_python/io/test.sh
Labels: PR: test

#7855 build: Adding b64 dependency to relevant targets (fix L0_build_variants)
  src/CMakeLists.txt
  src/python/tritonfrontend/CMakeLists.txt
Labels: build

#7882 build: Adding b64 dependency to relevant targets (fix L0_build_variants) (#7855)
  src/CMakeLists.txt
  src/python/tritonfrontend/CMakeLists.txt
Labels: cherry-pick

#7881 fix: Lock httpx version to fix L0_openai--trtllm test failures (#7870)
  python/openai/openai_frontend/main.py
  python/openai/requirements.txt
Labels: cherry-pick

#7837 ci: Fix Windows CI Errors
  qa/L0_backend_python/lifecycle/lifecycle_test.py
  qa/L0_backend_python/response_sender/response_sender_complete_final_test.py
  qa/L0_backend_python/response_sender/response_sender_test.py
  qa/L0_backend_python/response_sender/test.sh
  qa/L0_batcher/queue_timeout_test.py
  qa/L0_batcher/test.sh
  qa/L0_trt_plugin/test.sh
  qa/common/infer_util.py
Labels: PR: ci

#7858 perf: Upgrade vLLM version to 0.6.3.post1
  build.py
Labels: PR: perf
