Repository triton-inference-server/server, pull requests merged in 2024-08, with the labels that each got.

#7437 build: Add default value for argument 'TRITON_REPO_ORGANIZATION' from sdk Dockerfile
  Dockerfile.sdk
  docs/customization_guide/build.md
  docs/customization_guide/test.md
Labels: PR: build

#7504 test: Add test for sending response after sending complete final flag
  qa/L0_backend_python/response_sender/response_sender_complete_final_test.py
  qa/L0_backend_python/response_sender/test.sh
  qa/python_models/response_sender_complete_final/config.pbtxt
  qa/python_models/response_sender_complete_final/model.py
Labels: PR: test

#7493 feat: Add vLLM counter metrics access through Triton
  build.py
  docs/user_guide/metrics.md
Labels: enhancement

#7519 build: RHEL 8 Compatibility
  CMakeLists.txt
  build.py
  qa/L0_infer/install_and_test.sh
  src/CMakeLists.txt
Labels: module: platforms

#7525 test: Test histogram metric
  qa/python_models/custom_metrics/model.py
Labels: PR: test

#7546 feat: Add vLLM counter metrics access through Triton (#7493)
  build.py
  docs/user_guide/metrics.md
Labels: cherry-pick

#7545 test: Add python backend tests for the new histogram metric (#7540)
  qa/python_models/custom_metrics/model.py
Labels: cherry-pick

#7527 test: Load new model version should not reload loaded existing model version(s)
  qa/L0_lifecycle/lifecycle_test.py
  qa/L0_lifecycle/test.sh
Labels: PR: test

#7554 Intermittent `L0_decoupled_grpc_error` crash fixed. (#7552)
  src/grpc/infer_handler.h
Labels: cherry-pick

#7555 feat: Add GRPC error codes to GRPC streaming if enabled by user. (#7499)
  Dockerfile.QA
  docs/customization_guide/inference_protocols.md
  qa/L0_backend_python/lifecycle/lifecycle_test.py
  qa/L0_backend_python/lifecycle/test.sh
  qa/L0_decoupled/decoupled_test.py
  qa/L0_decoupled/test.sh
  qa/L0_grpc_state_cleanup/cleanup_test.py
  qa/python_models/execute_grpc_error/config.pbtxt
  qa/python_models/execute_grpc_error/model.py
  src/grpc/grpc_utils.h
  src/grpc/infer_handler.h
  src/grpc/stream_infer_handler.cc
Labels: cherry-pick

#7559 ci: Raise Documentation Generation Errors
  docs/generate_docs.py
Labels: PR: ci

#7563 docs: Add tensorrtllm_backend into doc generation
  docs/generate_docs.py
Labels: PR: docs

#7572 docs: Add python backend to windows build command
  docs/customization_guide/build.md
Labels: PR: docs

#7529 docs: Triton TRT-LLM user guide
  docs/getting_started/trtllm_user_guide.md
Labels: PR: docs
