Repository triton-inference-server/server, pull requests merged in 2024-09, with the labels that each got.

#7592 test: Refactor core input size checks
  qa/L0_input_validation/input_validation_test.py
  qa/L0_input_validation/test.sh
Labels: PR: test

#7606 Cherry-pick: Don't Build tritonfrontend for Windows
  src/CMakeLists.txt
Labels: cherry-pick

#7567 fix: Add reference count tracking for shared memory regions
  qa/L0_cuda_shared_memory/cuda_shared_memory_test.py
  qa/L0_cuda_shared_memory/test.sh
  qa/L0_shared_memory/shared_memory_test.py
  qa/L0_shared_memory/test.sh
  qa/L0_trt_shape_tensors/test.sh
  qa/python_models/execute_delayed_model/config.pbtxt
  qa/python_models/execute_delayed_model/model.py
  src/grpc/infer_handler.cc
  src/grpc/infer_handler.h
  src/grpc/stream_infer_handler.cc
  src/http_server.cc
  src/http_server.h
  src/shared_memory_manager.cc
  src/shared_memory_manager.h
Labels: PR: fix

#7595 build/test: RHEL8 EA3
  build.py
  qa/L0_sequence_batcher/test.sh
Labels: PR: build, PR: test

#7617 Fix: Add mutex lock for state completion check in gRPC streaming to prevent race condition
  src/grpc/stream_infer_handler.cc
Labels: PR: fix

#7619 Cherry-pick: Fix: Add mutex lock for state completion check in gRPC streaming to prevent race condition
  src/grpc/stream_infer_handler.cc
Labels: cherry-pick

#7634 ci: Set stability factor to a higher value
  qa/L0_perf_analyzer_capi/test.sh
Labels: module: clients
