Repository triton-inference-server/server, pull requests merged in 2025-06, with the labels that each got.

#8231 test: Ensemble async callback execution (rework)
  qa/L0_trace/test.sh
Labels: PR: test

#8236 test: Set correct log output stream
  qa/L0_logging/test.sh
  qa/common/util.sh
Labels: PR: test

#8174 fix: Update handling of large array sizes
  qa/L0_http/http_input_size_limit_test.py
  qa/L0_http/test.sh
  src/command_line_parser.cc
  src/command_line_parser.h
  src/common.h
  src/http_server.cc
  src/http_server.h
  src/main.cc
Labels: bug

#8255 ci: Fix onnx_model_store resnet_v1 name issues
  qa/L0_long_running_stress/scenarios.py
  qa/L0_long_running_stress/test.sh
Labels: PR: ci

#8259 ci: Fix L0_client_nobatch--base
  qa/L0_client_nobatch/test.sh
Labels: PR: ci

#8226 fix: Support max_completion_tokens option in OpenAI frontend
  python/openai/README.md
  python/openai/openai_frontend/engine/triton_engine.py
  python/openai/openai_frontend/engine/utils/triton.py
  python/openai/openai_frontend/main.py
  python/openai/openai_frontend/schemas/openai.py
  python/openai/tests/test_chat_completions.py
  python/openai/tests/test_openai_client.py
  python/openai/tests/test_tool_calling.py
  python/openai/tests/utils.py
Labels: PR: fix, openai

#8269 test: Remove shared memory key from the error response
  qa/python_models/bls_memory/model.py
  qa/python_models/bls_memory_async/model.py
Labels: PR: test
