Repository triton-inference-server/server, pull requests merged in 2025-08, with the labels that each got.

#8303 ci: Improve error handling for Python backend model initialization failures
  qa/L0_backend_python/test.sh
Labels: PR: ci

#8330 fix: Proper handling of system shm register offset
  qa/L0_shared_memory/shared_memory_test.py
  qa/L0_shared_memory/test.sh
  qa/common/infer_util.py
  src/shared_memory_manager.cc
Labels: bug

#8335 fix: System shared memory boundary check
  qa/L0_shared_memory/shared_memory_test.py
  src/shared_memory_manager.cc
Labels: PR: fix

#8336 fix: Improve validation for system shared memory register
  qa/L0_shared_memory/shared_memory_test.py
  qa/L0_shared_memory/test.sh
  src/common.cc
  src/common.h
  src/shared_memory_manager.cc
Labels: PR: fix

#8352 ci: Resolve CI failures (#8347)
  qa/L0_grpc/python_grpc_aio_test.py
Labels: PR: ci
