Repository triton-inference-server/server, pull requests merged in 2025-05, with the labels that each got.

#8170 Fix: Update handling of shared mem integer values
  qa/L0_shared_memory/shared_memory_test.py
  qa/L0_shared_memory/test.sh
  src/shared_memory_manager.cc
Labels: bug

#8172 fix: Add HTTP JSON parsing recursion depth limit
  qa/L0_http/http_test.py
  qa/L0_http/test.sh
  src/common.h
  src/http_server.cc
Labels: PR: fix

#8185 test: Add backend_api_test to test backend APIs
  Dockerfile.QA
  qa/L0_input_validation/test.sh
  src/test/CMakeLists.txt
  src/test/backend_tensor_size_test.cc
Labels: PR: test

#8182 Fix: Update element count handling
  qa/L0_http/http_test.py
  qa/L0_http/test.sh
  src/common.cc
  src/common.h
  src/http_server.cc
Labels: bug

#8220 fix: Improve cancellation handling for gRPC non-decoupled inference
  qa/L0_decoupled/decoupled_test.py
  qa/L0_decoupled/test.sh
  src/grpc/infer_handler.cc
Labels: bug
