Repository triton-inference-server/server, pull requests merged in 2025-07, with the labels that each got.

#8267 fix: Improve data type validation for classification
  qa/L0_parameters/class_count_test.py
  qa/L0_parameters/test.sh
  src/classification.cc
Labels: PR: fix

#8273 fix: Improve validation for system shared memory register
  qa/L0_shared_memory/shared_memory_test.py
  qa/L0_shared_memory/test.sh
  src/common.h
  src/shared_memory_manager.cc
Labels: PR: fix

#8264 feat: Add support for `usage` in the OpenAI frontend vLLM backend
  python/openai/README.md
  python/openai/openai_frontend/engine/triton_engine.py
  python/openai/openai_frontend/engine/utils/triton.py
  python/openai/openai_frontend/schemas/openai.py
  python/openai/tests/test_chat_completions.py
  python/openai/tests/test_completions.py
  python/openai/tests/test_lora.py
  python/openai/tests/test_openai_client.py
Labels: PR: feat, openai

#8305 refactor: Enhance memory allocation security in HTTP and Sagemaker request handler
  qa/L0_http/http_request_many_chunks.py
  qa/L0_http/test.sh
  qa/L0_sagemaker/sagemaker_request_many_chunks.py
  qa/L0_sagemaker/test.sh
  src/http_server.cc
  src/http_server.h
  src/sagemaker_server.cc
Labels: PR: refactor, DLIS-8401, TPRD-1628, DLIS-8402

#8314 refactor: Enhance memory allocation security in HTTP and Sagemaker request handler (#8305)
  qa/L0_http/http_request_many_chunks.py
  qa/L0_http/test.sh
  qa/L0_sagemaker/sagemaker_request_many_chunks.py
  qa/L0_sagemaker/test.sh
  src/http_server.cc
  src/http_server.h
  src/sagemaker_server.cc
Labels: cherry-pick, DLIS-8401, TPRD-1628, DLIS-8402

#8315 ci: Anchor datacenter-gpu-manager-4-core version
  Dockerfile.sdk
  build.py
Labels: PR: ci
