Repository triton-inference-server/server, pull requests merged in 2025-10, with the labels that each got.

#8431 test: Fix L0_simple_lib--base
  src/simple.cc
Labels: PR: test

#8436 test: Fix L0_simple_lib--base (#8431)
  src/simple.cc
Labels: cherry-pick

#8430 fix: Update L0_openai to adapt TRT-LLM v1.0
  qa/L0_openai/generate_engine.py
Labels: PR: fix
