Repository triton-inference-server/server, pull requests merged in 2025-04, with the labels that each got.

#8111 feat: ORCA Format KV Cache Utilization in Inference Response Header (…
  qa/common/orca_header_test.py
  src/CMakeLists.txt
  src/http_server.cc
  src/http_server.h
  src/orca_http.cc
  src/orca_http.h
Labels: cherry-pick

#8112 test: Add test for ORCA (#8009)
  qa/L0_orca/orca_http_test.py
  qa/L0_orca/test.sh
Labels: cherry-pick

#8116 ci: fix L0_lifecycle
  qa/L0_lifecycle/lifecycle_test.py
  qa/L0_lifecycle/test.sh
Labels: PR: ci

#8123 ci: Fix L0_infer--cpu* tests
  qa/L0_infer/test.sh
  qa/ensemble_models/mix_platform_float32_float32_float32/config.pbtxt
Labels: PR: ci

#8061 feat: Configurable grpc infer thread count
  docs/customization_guide/inference_protocols.md
  qa/L0_sequence_stress/test.sh
  src/command_line_parser.cc
  src/grpc/grpc_server.cc
  src/grpc/grpc_server.h
Labels: PR: feat

#8078 fix: Fix gRPC cancellation race condition
  qa/L0_request_cancellation/grpc_cancellation_test.py
  qa/L0_request_cancellation/test.sh
  src/grpc/infer_handler.cc
  src/grpc/infer_handler.h
  src/grpc/stream_infer_handler.cc
  src/grpc/stream_infer_handler.h
Labels: crash

#8144 fix: Fix segfaults in tracing mode after long run
  qa/L0_trace/test.sh
  qa/L0_trace/trace_stress_grpc_client.py
  src/tracer.cc
Labels: PR: fix

#8038 feat: Add multi-LoRA support to OpenAI frontend
  python/openai/README.md
  python/openai/openai_frontend/engine/triton_engine.py
  python/openai/openai_frontend/engine/utils/triton.py
  python/openai/openai_frontend/main.py
  python/openai/tests/test_lora.py
  python/openai/tests/utils.py
Labels: PR: feat

#8150 test: Add config parameter "execution_context_allocation_strategy" to TensorRT backend
  qa/L0_model_config/custom_parameters/tensorrt/invalid/allocation_strategy_invalid_value/expected
  qa/L0_model_config/custom_parameters/tensorrt/invalid/allocation_strategy_invalid_value/partial.pbtxt
  qa/L0_model_config/custom_parameters/tensorrt/valid/allocation_strategy_no_key/partial.pbtxt
  qa/L0_model_config/custom_parameters/tensorrt/valid/allocation_strategy_no_parameters/partial.pbtxt
  qa/L0_model_config/custom_parameters/tensorrt/valid/allocation_strategy_value_1/expected
  qa/L0_model_config/custom_parameters/tensorrt/valid/allocation_strategy_value_1/partial.pbtxt
  qa/L0_model_config/custom_parameters/tensorrt/valid/allocation_strategy_value_2/expected
  qa/L0_model_config/custom_parameters/tensorrt/valid/allocation_strategy_value_2/partial.pbtxt
  qa/L0_model_config/test.sh
  qa/common/check_copyright.py
Labels: PR: test

#8165 test: Input batch size overflow vulnerability
  qa/L0_input_validation/test.sh
Labels: PR: test

#7969 feat: Add graceful shutdown timer to GRPC frontend
  qa/L0_lifecycle/lifecycle_test.py
  qa/L0_lifecycle/test.sh
  src/grpc/grpc_server.cc
  src/grpc/grpc_server.h
  src/grpc/infer_handler.cc
  src/grpc/infer_handler.h
  src/grpc/stream_infer_handler.cc
  src/grpc/stream_infer_handler.h
  src/main.cc
Labels: enhancement, grpc
