Repository triton-inference-server/server, pull requests merged in 2025-09, with the labels that each got.

#8374 feat: Static key authentication for OpenAI frontend
  python/openai/README.md
  python/openai/openai_frontend/frontend/fastapi/middleware/__init__.py
  python/openai/openai_frontend/frontend/fastapi/middleware/api_restriction.py
  python/openai/openai_frontend/frontend/fastapi_frontend.py
  python/openai/openai_frontend/main.py
  python/openai/tests/test_openai_restricted_apis.py
  python/openai/tests/utils.py
  src/command_line_parser.cc
Labels: PR: feat

#8385 feat: Static key authentication for OpenAI frontend (#8374)
  python/openai/README.md
  python/openai/openai_frontend/frontend/fastapi/middleware/__init__.py
  python/openai/openai_frontend/frontend/fastapi/middleware/api_restriction.py
  python/openai/openai_frontend/frontend/fastapi_frontend.py
  python/openai/openai_frontend/main.py
  python/openai/tests/test_openai_restricted_apis.py
  python/openai/tests/utils.py
  src/command_line_parser.cc
Labels: cherry-pick

#8394 fix: Replace dead link for Densenet
  docs/user_guide/performance_tuning.md
Labels: documentation issue

#8408 ci: Remove deprecated vLLM config "disable_log_requests"
  python/openai/tests/vllm_mistral_models/mistral-nemo-instruct-2407/1/model.json
  python/openai/tests/vllm_models/llama-3.1-8b-instruct/1/model.json
  qa/L0_perf_vllm/test.sh
Labels: bug

#8405 ci: Fix CI failures
  qa/L0_long_running_stress/scenarios.py
  qa/L0_memory_growth/test.sh
  qa/L0_passive_instance/test.sh
  qa/L0_perf_deeprecommender/run_test.sh
  qa/L0_perf_nomodel/run_test.sh
  qa/L0_perf_resnet/run_test.sh
  qa/L0_pinned_memory/test.sh
  qa/L0_response_cache/test.sh
  qa/L0_trt_dynamic_shape/test.sh
Labels: PR: ci

#8409 ci: Fix L0_client_build_variants and L0_sdk tests
  qa/L0_client_build_variants/test.sh
  qa/L0_sdk/test.sh
Labels: PR: ci

#8411 fix: Replace Use of `alloca`
  src/data_compressor.h
  src/test/data_compressor_test.cc
Labels: bug, PR: fix, memory
